---
# Описывает все управляемые сервера.
# Замените ansible_host на реальные IP-адреса ваших серверов.

all:
  children:
    servers:
      hosts:
        server-1:
          ansible_host: 10.76.229.152
        server-2:
          ansible_host: 10.76.229.52
        server-3:
          ansible_host: 10.76.229.97

    swarm_managers:
      hosts:
        swarm-manager:
          ansible_host: 10.76.229.119
